### ISSUE TITLE
Add solution file

### ISSUE THREAD

**Issue by Vtek** [GyozaTeam/Gyoza#22]
### Description
Currently no solution are available. It isn't a problem for CI and VS Code, but Visual Studio need it.

### Acceptances & rules
- [x] Create a solution file with all project references.

**Comment by JulienPavon** [comment]
Usefull to execute test on solution instead of each test project.

Why is there a test directory ? Test source code is as important as production source code.

**Comment by Vtek** [comment]
I agree!

Currently I don't need solution because I work only on VS Code, but feel free to add it.
Test folder is just repository organisation (it looks like dotnet core repository organisation)
